Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 4096
  end
#  config.vbguest.installer_options = { allow_kernel_upgrade: true }
#  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
end
